### PR TITLE
Fix HTML1409 and HTML1423 errors

### PR DESCRIPTION
**Pull request by willbar**
@Snesha could you review and merge this? I'll do another PR for the SEC7115 issue.

### CODE REVIEW

**Comment by Snesha** [comment]
LGTM and I assume tested with Chrome too?

**Comment by willbar** [comment]
Yes

Regards,

William Bartholomew
Open Source Programs Office

We’re hiring! The Open Source Programs Office is looking for PMs and engineers passionate about open source @ Microsoft. Visit http://aka.ms/ospojobsinternal or email me for more information.

**Comment by Snesha** [comment]
Merged

**Comment by PixleProgrambetaxl** [comment]
+1

**Pull request merged**
